---
- name: Deploy MongoDB with Community Operator
  hosts: localhost
  gather_facts: false
  connection: local
  become: false
  vars:
    kubeconfig: "{{ lookup('env', 'KUBECONFIG') | default('~/.kube/config', true) }}"
    kube_context: "" # Set to your context if needed, else leave blank
    deployment_namespace: "databases"
    infisical_host_api: "https://infisical.infra.slick.ge/api"
    identity_id: "998c1306-87ff-4b1e-9225-2f82ef8d5fff"
    project_slug: "infra-resources-b-ou-q"
    env_slug: "homelablocal"
    secrets_path: "/mongodb"
    mongodb_ingress_host: "mongo-express.infra.k8s.slick.ge"
    mongodb_version: "6.0.5"
    mongodb_replicas: 3
    storage_class: "longhorn"
    storage_size: "2Gi"  # Reduced from 5Gi due to limited Longhorn storage
    mongodb_nodeport: 30017  # External port for MongoDB access

  tasks:
    - name: Create databases namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ deployment_namespace }}"
        kubeconfig: "{{ kubeconfig }}"
        context: "{{ kube_context if kube_context else omit }}"

    - name: Create MongoDB Operator ServiceAccount
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: ServiceAccount
          metadata:
            name: mongodb-kubernetes-operator
            namespace: "{{ deployment_namespace }}"
        kubeconfig: "{{ kubeconfig }}"
        context: "{{ kube_context if kube_context else omit }}"

    - name: Create MongoDB Database ServiceAccount
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: ServiceAccount
          metadata:
            name: mongodb-database
            namespace: "{{ deployment_namespace }}"
        kubeconfig: "{{ kubeconfig }}"
        context: "{{ kube_context if kube_context else omit }}"

    - name: Create MongoDB Database Role
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: rbac.authorization.k8s.io/v1
          kind: Role
          metadata:
            name: mongodb-database
            namespace: "{{ deployment_namespace }}"
          rules:
          - apiGroups: [""]
            resources: ["secrets", "configmaps", "pods", "services"]
            verbs: ["get", "list", "watch", "patch", "update"]
        kubeconfig: "{{ kubeconfig }}"
        context: "{{ kube_context if kube_context else omit }}"

    - name: Create MongoDB Database RoleBinding
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: rbac.authorization.k8s.io/v1
          kind: RoleBinding
          metadata:
            name: mongodb-database
            namespace: "{{ deployment_namespace }}"
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: Role
            name: mongodb-database
          subjects:
          - kind: ServiceAccount
            name: mongodb-database
            namespace: "{{ deployment_namespace }}"
        kubeconfig: "{{ kubeconfig }}"
        context: "{{ kube_context if kube_context else omit }}"

    - name: Create MongoDB Operator ClusterRole
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: rbac.authorization.k8s.io/v1
          kind: ClusterRole
          metadata:
            name: mongodb-kubernetes-operator
          rules:
          - apiGroups: [""]
            resources: ["pods", "services", "endpoints", "persistentvolumeclaims", "events", "configmaps", "secrets"]
            verbs: ["*"]
          - apiGroups: ["apps"]
            resources: ["deployments", "daemonsets", "replicasets", "statefulsets"]
            verbs: ["*"]
          - apiGroups: ["mongodbcommunity.mongodb.com"]
            resources: ["mongodbcommunity", "mongodbcommunity/status", "mongodbcommunity/spec", "mongodbcommunity/finalizers"]
            verbs: ["*"]
        kubeconfig: "{{ kubeconfig }}"
        context: "{{ kube_context if kube_context else omit }}"

    - name: Create MongoDB Operator ClusterRoleBinding
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: rbac.authorization.k8s.io/v1
          kind: ClusterRoleBinding
          metadata:
            name: mongodb-kubernetes-operator
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: ClusterRole
            name: mongodb-kubernetes-operator
          subjects:
          - kind: ServiceAccount
            name: mongodb-kubernetes-operator
            namespace: "{{ deployment_namespace }}"
        kubeconfig: "{{ kubeconfig }}"
        context: "{{ kube_context if kube_context else omit }}"

    - name: Install MongoDB Community Operator
      kubernetes.core.k8s:
        state: present
        src: "https://raw.githubusercontent.com/mongodb/mongodb-kubernetes-operator/master/config/crd/bases/mongodbcommunity.mongodb.com_mongodbcommunity.yaml"
        kubeconfig: "{{ kubeconfig }}"
        context: "{{ kube_context if kube_context else omit }}"
        namespace: "{{ deployment_namespace }}"

    - name: Install MongoDB Community Operator deployment
      kubernetes.core.k8s:
        state: present
        src: "https://raw.githubusercontent.com/mongodb/mongodb-kubernetes-operator/master/config/manager/manager.yaml"
        kubeconfig: "{{ kubeconfig }}"
        context: "{{ kube_context if kube_context else omit }}"
        namespace: "{{ deployment_namespace }}"

    - name: Create InfisicalSecret for MongoDB credentials
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: secrets.infisical.com/v1alpha1
          kind: InfisicalSecret
          metadata:
            name: mongodb-auth
            namespace: "{{ deployment_namespace }}"
          spec:
            hostAPI: "{{ infisical_host_api }}"
            resyncInterval: 10
            authentication:
              kubernetesAuth:
                identityId: "{{ identity_id }}"
                serviceAccountRef:
                  name: infisical-service-account
                  namespace: infisical
                secretsScope:
                  envSlug: "{{ env_slug }}"
                  projectSlug: "{{ project_slug }}"
                  secretsPath: "{{ secrets_path }}"
            managedKubeSecretReferences:
              - secretName: mongodb-auth
                secretNamespace: "{{ deployment_namespace }}"
                creationPolicy: Orphan
                template:
                  includeAllSecrets: false
                  data:
                    password: "{{ '{{' }} .MONGODB_ROOT_PASSWORD.Value {{ '}}' }}"
        kubeconfig: "{{ kubeconfig }}"
        context: "{{ kube_context if kube_context else omit }}"

    - name: Deploy MongoDB Replica Set
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: mongodbcommunity.mongodb.com/v1
          kind: MongoDBCommunity
          metadata:
            name: mongodb
            namespace: "{{ deployment_namespace }}"
          spec:
            members: "{{ mongodb_replicas }}"
            type: ReplicaSet
            version: "{{ mongodb_version }}"
            security:
              authentication:
                modes: ["SCRAM"]
            users:
              - name: admin
                db: admin
                passwordSecretRef:
                  name: mongodb-auth
                  key: password
                roles:
                  - name: clusterAdmin
                    db: admin
                  - name: userAdminAnyDatabase
                    db: admin
                  - name: dbAdminAnyDatabase
                    db: admin
                  - name: readWriteAnyDatabase
                    db: admin
                scramCredentialsSecretName: mongodb-scram
            additionalMongodConfig:
              storage.wiredTiger.engineConfig.journalCompressor: snappy
            statefulSet:
              spec:
                template:
                  metadata:
                    annotations:
                      prometheus.io/scrape: "true"
                      prometheus.io/port: "9216"
                  spec:
                    containers:
                      - name: mongodb-agent
                        resources:
                          requests:
                            cpu: 100m
                            memory: 128Mi
                          limits:
                            cpu: 500m
                            memory: 512Mi
                      - name: mongod
                        resources:
                          requests:
                            cpu: 500m
                            memory: 1Gi
                          limits:
                            cpu: 2
                            memory: 4Gi
                      - name: mongodb-exporter
                        image: percona/mongodb_exporter:0.40
                        args:
                          - --mongodb.uri=mongodb://admin:$(MONGODB_PASSWORD)@localhost:27017/admin
                          - --collect-all
                        env:
                          - name: MONGODB_PASSWORD
                            valueFrom:
                              secretKeyRef:
                                name: mongodb-auth
                                key: password
                        ports:
                          - containerPort: 9216
                            name: metrics
                volumeClaimTemplates:
                  - metadata:
                      name: data-volume
                    spec:
                      accessModes:
                        - ReadWriteOnce
                      storageClassName: "{{ storage_class }}"
                      resources:
                        requests:
                          storage: "{{ storage_size }}"
                  - metadata:
                      name: logs-volume
                    spec:
                      accessModes:
                        - ReadWriteOnce
                      storageClassName: "{{ storage_class }}"
                      resources:
                        requests:
                          storage: 1Gi
        kubeconfig: "{{ kubeconfig }}"
        context: "{{ kube_context if kube_context else omit }}"

    - name: Create NodePort Service for external MongoDB access
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: mongodb-external
            namespace: "{{ deployment_namespace }}"
            labels:
              app: mongodb-svc
          spec:
            type: NodePort
            selector:
              app: mongodb-svc
            ports:
              - port: 27017
                targetPort: 27017
                nodePort: "{{ mongodb_nodeport }}"
                protocol: TCP
                name: mongodb
        kubeconfig: "{{ kubeconfig }}"
        context: "{{ kube_context if kube_context else omit }}"

    - name: Create InfisicalSecret for Mongo Express credentials
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: secrets.infisical.com/v1alpha1
          kind: InfisicalSecret
          metadata:
            name: mongo-express-auth
            namespace: "{{ deployment_namespace }}"
          spec:
            hostAPI: "{{ infisical_host_api }}"
            resyncInterval: 10
            authentication:
              kubernetesAuth:
                identityId: "{{ identity_id }}"
                serviceAccountRef:
                  name: infisical-service-account
                  namespace: infisical
                secretsScope:
                  envSlug: "{{ env_slug }}"
                  projectSlug: "{{ project_slug }}"
                  secretsPath: "{{ secrets_path }}"
            managedKubeSecretReferences:
              - secretName: mongo-express-auth
                secretNamespace: "{{ deployment_namespace }}"
                creationPolicy: Orphan
                template:
                  includeAllSecrets: false
                  data:
                    username: "{{ '{{' }} .MONGO_EXPRESS_USERNAME.Value {{ '}}' }}"
                    password: "{{ '{{' }} .MONGO_EXPRESS_PASSWORD.Value {{ '}}' }}"
        kubeconfig: "{{ kubeconfig }}"
        context: "{{ kube_context if kube_context else omit }}"

    - name: Deploy Mongo Express Web UI
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: mongo-express
            namespace: "{{ deployment_namespace }}"
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: mongo-express
            template:
              metadata:
                labels:
                  app: mongo-express
              spec:
                containers:
                  - name: mongo-express
                    image: mongo-express:1.0-20
                    ports:
                      - containerPort: 8081
                    env:
                      - name: ME_CONFIG_MONGODB_ADMINUSERNAME
                        value: admin
                      - name: ME_CONFIG_MONGODB_ADMINPASSWORD
                        valueFrom:
                          secretKeyRef:
                            name: mongodb-auth
                            key: password
                      - name: ME_CONFIG_MONGODB_SERVER
                        value: "mongodb-0.mongodb-svc.{{ deployment_namespace }}.svc.cluster.local,mongodb-1.mongodb-svc.{{ deployment_namespace }}.svc.cluster.local,mongodb-2.mongodb-svc.{{ deployment_namespace }}.svc.cluster.local"
                      - name: ME_CONFIG_MONGODB_PORT
                        value: "27017"
                      - name: ME_CONFIG_MONGODB_AUTH_DATABASE
                        value: admin
                      - name: ME_CONFIG_BASICAUTH_USERNAME
                        valueFrom:
                          secretKeyRef:
                            name: mongo-express-auth
                            key: username
                      - name: ME_CONFIG_BASICAUTH_PASSWORD
                        valueFrom:
                          secretKeyRef:
                            name: mongo-express-auth
                            key: password
                    resources:
                      requests:
                        cpu: 100m
                        memory: 128Mi
                      limits:
                        cpu: 500m
                        memory: 512Mi
        kubeconfig: "{{ kubeconfig }}"
        context: "{{ kube_context if kube_context else omit }}"

    - name: Create Service for Mongo Express
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: mongo-express
            namespace: "{{ deployment_namespace }}"
          spec:
            type: ClusterIP
            selector:
              app: mongo-express
            ports:
              - port: 8081
                targetPort: 8081
        kubeconfig: "{{ kubeconfig }}"
        context: "{{ kube_context if kube_context else omit }}"

    - name: Create Ingress for Mongo Express Web UI
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: mongo-express
            namespace: "{{ deployment_namespace }}"
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
          spec:
            ingressClassName: nginx
            tls:
              - hosts:
                  - "{{ mongodb_ingress_host }}"
                secretName: mongo-express-tls
            rules:
              - host: "{{ mongodb_ingress_host }}"
                http:
                  paths:
                    - path: /
                      pathType: Prefix
                      backend:
                        service:
                          name: mongo-express
                          port:
                            number: 8081
        kubeconfig: "{{ kubeconfig }}"
        context: "{{ kube_context if kube_context else omit }}"

    - name: Create ServiceMonitor for MongoDB metrics
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: monitoring.coreos.com/v1
          kind: ServiceMonitor
          metadata:
            name: mongodb-metrics
            namespace: "{{ deployment_namespace }}"
            labels:
              app.kubernetes.io/name: mongodb
              release: kube-prometheus-stack
          spec:
            selector:
              matchLabels:
                app: mongodb-svc
            endpoints:
              - port: metrics
                interval: 30s
                path: /metrics
        kubeconfig: "{{ kubeconfig }}"
        context: "{{ kube_context if kube_context else omit }}"

    - name: Wait for MongoDB replica set to be ready
      kubernetes.core.k8s_info:
        kind: MongoDBCommunity
        name: mongodb
        namespace: "{{ deployment_namespace }}"
        kubeconfig: "{{ kubeconfig }}"
        context: "{{ kube_context if kube_context else omit }}"
        wait: true
        wait_condition:
          type: Ready
          status: "True"
        wait_timeout: 600

    - name: Get MongoDB connection info
      kubernetes.core.k8s_info:
        kind: Secret
        name: mongodb-auth
        namespace: "{{ deployment_namespace }}"
        kubeconfig: "{{ kubeconfig }}"
        context: "{{ kube_context if kube_context else omit }}"
      register: mongodb_secret

    - name: Get cluster node IPs
      kubernetes.core.k8s_info:
        kind: Node
        kubeconfig: "{{ kubeconfig }}"
        context: "{{ kube_context if kube_context else omit }}"
      register: cluster_nodes

    - name: Display MongoDB access information
      debug:
        msg:
          - "=== MongoDB Cluster Information ==="
          - "Mongo Express UI: https://{{ mongodb_ingress_host }}"
          - ""
          - "=== Internal Access (from within cluster) ==="
          - "Connection String: mongodb://admin:PASSWORD@mongodb-svc.{{ deployment_namespace }}.svc.cluster.local:27017/admin?replicaSet=mongodb"
          - "Service: mongodb-svc.{{ deployment_namespace }}.svc.cluster.local:27017"
          - ""
          - "=== External Access (from outside cluster) ==="
          - "NodePort: {{ mongodb_nodeport }}"
          - "Connect using any node IP: mongodb://admin:PASSWORD@<NODE_IP>:{{ mongodb_nodeport }}/admin?replicaSet=mongodb"
          - "Available node IPs: {{ cluster_nodes.resources | map(attribute='status.addresses') | flatten | selectattr('type', 'equalto', 'InternalIP') | map(attribute='address') | list | join(', ') }}"
          - ""
          - "=== Credentials ==="
          - "Username: admin"
          - "Password stored in secret: mongodb-auth"
          - ""
          - "To get the password, run:"
          - "kubectl get secret mongodb-auth -n {{ deployment_namespace }} -o jsonpath='{.data.password}' | base64 -d"
          - ""
          - "=== Example Connection Commands ==="
          - "MongoDB Shell: mongosh 'mongodb://admin:PASSWORD@<NODE_IP>:{{ mongodb_nodeport }}/admin'"
          - "Python: MongoClient('mongodb://admin:PASSWORD@<NODE_IP>:{{ mongodb_nodeport }}/admin')"
