---
- name: Prepare nodes for Longhorn storage
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Install open-iscsi (required for Longhorn)
      ansible.builtin.apt:
        name:
          - open-iscsi
          - nfs-common
          - util-linux
        state: present
        update_cache: true

    - name: Enable and start iscsid service
      ansible.builtin.systemd:
        name: iscsid
        enabled: true
        state: started
        daemon_reload: true

    - name: Check if multipathd is installed
      ansible.builtin.command: which multipathd
      register: multipathd_check
      ignore_errors: true
      changed_when: false

    - name: Disable multipathd if present (can conflict with Longhorn)
      ansible.builtin.systemd:
        name: multipathd
        enabled: false
        state: stopped
      when: multipathd_check.rc == 0
      ignore_errors: true

    - name: Ensure /var/lib/longhorn directory exists
      ansible.builtin.file:
        path: /var/lib/longhorn
        state: directory
        mode: '0755'

    - name: Check available disk space
      ansible.builtin.shell: df -h /var/lib/longhorn | tail -1 | awk '{print $4}'
      register: disk_space
      changed_when: false

    - name: Display available disk space
      ansible.builtin.debug:
        msg: "Available disk space on {{ inventory_hostname }}: {{ disk_space.stdout }}"

- name: Deploy Longhorn distributed storage system
  hosts: localhost
  gather_facts: false
  connection: local
  become: false
  
  vars:
    kubeconfig: "{{ lookup('env', 'KUBECONFIG') | default('~/.kube/config', true) }}"
    kube_context: ""
    deployment_namespace: longhorn-system
    longhorn_url: "longhorn.infra.k8s.slick.ge"
    longhorn_s3_backup_target: "s3://slickg@weur/longhorn_hetzner"
    # Infisical configuration
    infisical_host_api: "https://infisical.infra.slick.ge/api"
    identity_id: "998c1306-87ff-4b1e-9225-2f82ef8d5fff"
    project_slug: "infra-resources-b-ou-q"
    env_slug: "homelablocal"
    secrets_path: "/longhorn"
  tasks:
    - name: Ensure longhorn Helm repo is present
      kubernetes.core.helm_repository:
        name: longhorn
        repo_url: https://charts.longhorn.io

    - name: Create longhorn namespace
      kubernetes.core.k8s:
        name: "{{ deployment_namespace }}"
        api_version: v1
        kind: Namespace
        state: present

    - name: Create InfisicalSecret for Longhorn secrets
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: secrets.infisical.com/v1alpha1
          kind: InfisicalSecret
          metadata:
            name: longhorn-secrets
            namespace: "{{ deployment_namespace }}"
          spec:
            hostAPI: "{{ infisical_host_api }}"
            resyncInterval: 10
            authentication:
              kubernetesAuth:
                identityId: "{{ identity_id }}"
                serviceAccountRef:
                  name: infisical-service-account
                  namespace: infisical
                secretsScope:
                  envSlug: "{{ env_slug }}"
                  projectSlug: "{{ project_slug }}"
                  secretsPath: "{{ secrets_path }}"
            managedKubeSecretReferences:
              - secretName: longhorn-s3-auth
                secretNamespace: "{{ deployment_namespace }}"
                creationPolicy: Orphan
                template:
                  includeAllSecrets: false
                  data:
                    AWS_ACCESS_KEY_ID: "{{ '{{' }} .S3_ACCESS_KEY.Value {{ '}}' }}"
                    AWS_SECRET_ACCESS_KEY: "{{ '{{' }} .S3_SECRET_KEY.Value {{ '}}' }}"
                    AWS_ENDPOINTS: "{{ '{{' }} .S3_ENDPOINT.Value {{ '}}' }}"
              - secretName: longhorn-auth-id
                secretNamespace: "{{ deployment_namespace }}"
                creationPolicy: Orphan
                template:
                  includeAllSecrets: false
                  data:
                    auth: "{{ '{{' }} .LONGHORN_UI_AUTH.Value {{ '}}' }}"

    - name: Deploy Longhorn via Helm
      kubernetes.core.helm:
        name: longhorn
        chart_ref: longhorn/longhorn
        release_namespace: "{{ deployment_namespace }}"
        create_namespace: true
        values:

          #If need be use below as 'values.yaml'

          # Longhorn configuration for Hetzner homelab
          # 3-node cluster: 1 control-plane + 2 workers
          defaultBackupStoreSettings:
            # Storage settings
            defaultReplicaCount: 2  # 2 replicas for HA (max we can do with 2 workers)
            guaranteedEngineManagerCPU: 5  # CPU reservation percentage
            guaranteedReplicaManagerCPU: 5
            # Backup settings (optional - configure S3 if needed)
            backupTarget: "{{ longhorn_s3_backup_target }}"  # e.g., "s3://bucket@region/path" for Hetzner Object Storage
            backupTargetCredentialSecret: "longhorn-s3-auth"
            # Node selector - exclude control plane from storage
            createDefaultDiskLabeledNodes: true
            defaultDataPath: /var/lib/longhorn
            # Performance tuning for smaller nodes
            storageOverProvisioningPercentage: 200
            storageMinimalAvailablePercentage: 5
            # Auto-salvage and recovery
            autoSalvage: true
            autoDeletePodWhenVolumeDetachedUnexpectedly: true
          persistence:
            defaultClass: true  # Make longhorn the default StorageClass
            defaultClassReplicaCount: 2
            reclaimPolicy: Delete
            migratable: true
          ingress:
            enabled: true
            ingressClassName: nginx
            host: "{{ longhorn_url }}"
            tls: true
            tlsSecret: longhorn-tls
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
              nginx.ingress.kubernetes.io/auth-type: basic
              nginx.ingress.kubernetes.io/auth-secret: longhorn-auth-id
              nginx.ingress.kubernetes.io/auth-realm: "Longhorn - Authentication Required"
          longhornManager:
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 500m
                memory: 512Mi
          longhornDriver:
            resources:
              requests:
                cpu: 50m
                memory: 64Mi
              limits:
                cpu: 200m
                memory: 256Mi
          longhornUI:
            resources:
              requests:
                cpu: 50m
                memory: 64Mi
              limits:
                cpu: 200m
                memory: 256Mi
            #till here    
        kubeconfig: "{{ kubeconfig }}"
        context: "{{ kube_context if kube_context else omit }}"
        wait: true
        timeout: 10m
        atomic: true
        update_repo_cache: true

    - name: Wait for Longhorn manager pods to be ready
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Pod
        namespace: "{{ deployment_namespace }}"
        label_selectors:
          - app=longhorn-manager
        kubeconfig: "{{ kubeconfig }}"
      register: manager_pods
      retries: 30
      delay: 10
      until: >
        manager_pods.resources | length > 0 and
        manager_pods.resources | selectattr('status.phase', 'equalto', 'Running') | list | length ==
        manager_pods.resources | length

    - name: Display Longhorn UI access information
      ansible.builtin.debug:
        msg: 
          - "Longhorn deployment complete!"
          - "UI available at: {{ longhorn_url }}"
          - "Check status: kubectl -n longhorn-system get pods"
          - "View StorageClass: kubectl get storageclass longhorn"