apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dev
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: mymail@mail.com
    privateKeySecretRef:
      name: letsencrypt-dev
    solvers:
      - http01:
          ingress:
            class: nginx
