version: '3'
services:
    ansible:
        image: ghvinerias/ansible:bw
        restart: "no"
        volumes:
          - ../Ansible/tunnel-config.yml:/app/tunnel-config.yml:ro
          - ../Ansible/tunnel_configs:/app/tunnel_configs
          - ./tunnel_data:/output
    
    cloudflared:
        image: cloudflare/cloudflared
        restart: unless-stopped
        command: tunnel --config /root/.cloudflared/config.yml run dev-tools
        volumes:
          - ./tunnel_data:/root/.cloudflared/
        depends_on:
            ansible:
                condition: service_completed_successfully
    echo:
        image: mendhak/http-https-echo:31
        environment:
            - HTTP_PORT=8888
        ports:
            - "8080:8888"
    it-tools:
        image: corentinth/it-tools:latest
        ports:
            - "8081:80"
