---
- name: Declare and Echo Vars on Local Host
  hosts: localhost
  gather_facts: false

  vars:
    secret_id: "{{ lookup('env', 'SECRET_ID') }}"
    tunnel_id: "{{ lookup('bitwarden.secrets.lookup', secret_id, field='key') }}"
    tunnel_auth: "{{ lookup('bitwarden.secrets.lookup', secret_id, field='value') }}"
    tunnel_cert: "{{ lookup('bitwarden.secrets.lookup', secret_id, field='note') }}"

  tasks:
    - name: Check if variable is not "default"
      ansible.builtin.assert:
        that:
          - secret_id != "default_value"
        fail_msg: "Variable 'SECRET_ID' should not be 'default_value'"
        success_msg: "Variable 'SECRET_ID' is valid"

    - name: Set Tunnel Auth JSON
      ansible.builtin.set_fact:
        tunnel_auth_json: "{{ tunnel_auth | to_json }}"

    - name: Print Tunnel Auth
      ansible.builtin.copy:
        content: "{{ tunnel_auth_json }}"
        dest: "/output/{{ tunnel_id }}.json"
        mode: "0400"

    - name: Print Tunnel Cert
      ansible.builtin.copy:
        content: "{{ tunnel_cert }}"
        dest: "/output/cert.pem"
        mode: "0600"

    - name: Template a file, using symbolic modes (equivalent to 0644)
      ansible.builtin.template:
        src: "./tunnel_configs/{{ tunnel_id }}.yml"
        dest: "/output/config.yml"
        owner: root
        group: root
        mode: u=rw,g=r,o=r
