version: '3'
services:
    echo:
        image: mendhak/http-https-echo:31
        environment:
            - HTTP_PORT=8888
        ports:
            - "8080:8888"
    it-tools:
        image: corentinth/it-tools:latest
        ports:
            - "8081:80"